<?php 

$_product = $this->getProduct();
$_price = $_product->getPrice();
$_msrp = $_product->getMsrp();
$_oran = ( ( $_msrp - $_price ) / $_msrp ) * 100;


?>
<?php if($_price >= $_msrp){ ?>


<div class="kolayoto-price-box">
	<div class="regular-price">
		<div class="price">
			<?php echo Mage::app()->getStore()->formatPrice($_price) ?>
		</div>
	</div>
</div>



<?php }else{ ?> 

<div class="kolayoto-price-box">
	<div class="discount-rate right">
		<div class="rate">
			<?php echo "%".round($_oran) ?>
		</div>
		<div class="rate-label"><?php echo $this->__('indirim'); ?></div>
	</div>
	<div class="old-price">
		<div class="price">
			<?php echo Mage::app()->getStore()->formatPrice($_msrp) ?>
		</div>
		<div class="price-label"><?php echo $this->__('yerine'); ?></div>
	</div>
	<div class="special-price">
		<div class="price">
			<?php echo Mage::app()->getStore()->formatPrice($_price) ?>
		</div>
	</div>
	
</div>


<?php }?>

